Repository PyCQA/doc8, pull requests merged in 2020-08, with the labels that each got.

#38 Turn off pre-commit's automated multiprocessing
  .pre-commit-hooks.yaml
Labels: enhancement

#39 Add release-drafter
  .github/labels.yml
  .github/release-drafter.yml
  .github/workflows/release-drafter.yml
Labels: skip-changelog

#40 Enable testing with github actions
  .github/workflows/tox.yml
Labels: skip-changelog

#41 Add docs tox environment to github actions
  .github/workflows/tox.yml
Labels: skip-changelog

#42 Replace travis with github actions
  .github/workflows/tox.yml
  .travis.yml
Labels: skip-changelog

#43 Fix CI badge
  README.rst
Labels: skip-changelog

#44 Add support for py38
  .github/workflows/tox.yml
  setup.cfg
  tox.ini
Labels: enhancement

#45 Remove support for py27 and py35
  .github/workflows/tox.yml
  doc8/checks.py
  doc8/main.py
  doc8/parser.py
  doc8/tests/test_main.py
  requirements.txt
  setup.cfg
  tox.ini
Labels: major

#46 Remove chardet based input encoding detection
  README.rst
  doc8/main.py
  doc8/parser.py
  doc8/tests/test_main.py
  requirements.txt
Labels: major
