Repository PyCQA/doc8, pull requests merged in 2021-07, with the labels that each got.

#56 Add pyproject.toml support to README
  README.rst
Labels: bug

#59 Maintenance of release workflow
  .github/CODEOWNERS
  .github/release-drafter.yml
  .github/workflows/labels.yml
  .github/workflows/release-drafter.yml
  .github/workflows/release.yml
  .github/workflows/tox.yml
Labels: skip-changelog

#60 Bump linters and enable mypy
  .pre-commit-config.yaml
  mypy.ini
Labels: skip-changelog

#61 Add support for py39
  .github/workflows/tox.yml
  setup.cfg
  tox.ini
Labels: major
