Repository PyCQA/doc8, pull requests merged in 2022-07, with the labels that each got.

#95 Add support for python 3.11
  .github/workflows/tox.yml
  setup.cfg
Labels: bug

#96 GHA maintenance
  .github/dependabot.yml
  .github/workflows/tox.yml
Labels: skip-changelog

#94 Remove pip from `pyproject.toml`
  pyproject.toml
Labels: bug

#99 More GHA maintenance
  .github/FUNDING.yml
  .github/release-drafter.yml
  .github/workflows/ack.yml
  .github/workflows/labels.yml
  .github/workflows/release-drafter.yml
Labels: skip-changelog

#100 Avoid using py311 with pylint
  .github/workflows/tox.yml
  .pre-commit-config.yaml
Labels: skip-changelog

#101 Drop support for python 3.6
  .github/workflows/tox.yml
  setup.cfg
Labels: major

#93 Make toml support implicit
  README.rst
  setup.cfg
  src/doc8/main.py
Labels: bug

#102 Add missing push workflow
  .github/workflows/push.yml
Labels: skip-changelog

#103 Address some deprecation warnings
  pytest.ini
  setup.cfg
  src/doc8/checks.py
  src/doc8/utils.py
  tox.ini
Labels: bug

#105 Switch to v1 for pypa/gh-action-pypi-publish
  .github/workflows/release.yml
Labels: bug, skip-changelog
