Repository PyCQA/doc8, pull requests merged in 2022-12, with the labels that each got.

#117 Update tox.ini for tox v4
  tox.ini
Labels: skip-changelog

#116 Allow PEP links with anchors
  src/doc8/checks.py
Labels: bug

#118 Clear dotfiles
  .gitreview
  .pylintrc
  mypy.ini
  pyproject.toml
  pytest.ini
Labels: skip-changelog

#119 Remove use of pbr
  .gitignore
  doc/requirements.txt
  pyproject.toml
  src/doc8/__init__.py
  src/doc8/main.py
  src/doc8/version.py
Labels: bug

#121 Adopt GHA dynamic-matrix
  .github/workflows/tox.yml
Labels: skip-changelog

#122 Remove support for py37 and enable support for py312
  .pre-commit-config.yaml
  pyproject.toml
  src/doc8/checks.py
  src/doc8/main.py
  src/doc8/parser.py
  src/doc8/tests/test_checks.py
  src/doc8/tests/test_main.py
  src/doc8/utils.py
  src/doc8/version.py
Labels: feature, skip-changelog
