Repository PyCQA/doc8, pull requests merged in 2022-03, with the labels that each got.

#76 Add ability to load .config/doc8.ini
  README.rst
  src/doc8/main.py
Labels: enhancement

#79 Bump pre-commit hooks
  .pre-commit-config.yaml
Labels: skip-changelog

#81 Use tomli to read .toml files
  .pre-commit-config.yaml
  README.rst
  src/doc8/main.py
  test-requirements.txt
Labels: bug
